name: SSM_BY_PATH
description: Retrieve parameters from ssm using path prefix
author: https://github.com/lendi-au/ssm-by-path-buildkite-plugin
public: true
requirements:
  - aws
  - bash
  - jq
configuration:
  properties:
    assume-role-arn:
      type: string
    ssmpath:
      type: string
    recursive:
      type: string
  required:
    - ssmpath